name: Testing Url

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * 1"

jobs:
  url-health-check:
    name: Check the deployed service URL
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check URL health
        uses: jtalk/url-health-check-action@v4
        with:
          url: "https://full-stack-web-development-part-11.onrender.com/"
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
